
SENDGRID_PASSWORD: alicia16
SENDGRID_USERNAME: app36309919@heroku.com

DEVISE_SECRET_KEY:  thegeneratedtoken 

 AWS_ACCESS_KEY_ID: AKIAJARZVU2DV3V5W7HQ
 AWS_SECRET_ACCESS_KEY: JSRwZuZbOn3gnimF+8af0w1yfvEKoTirjL8Ko+D
 development:
   AWS_BUCKET: bloccit-development-junko
 production:
   AWS_BUCKET: uploading-img-bloccit-production


